sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t rakesh/docker-react -f Dockerfile.dev . 

script: 
   - docker run --env CI=true rakesh/docker-react npm run test -- --coverage     