sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t rakesh/docker-react -f Dockerfile.dev . 

script: 
   - docker run --env CI=true rakesh/docker-react npm run test -- --coverage  

deploy: 
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-292917023293"
    bucket_path: "docker-react"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

